# Generated by Django 5.1.3 on 2024-12-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='color',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
