# Generated by Django 5.1.3 on 2025-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0016_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='file',
        ),
    ]
