# Generated by Django 5.1.3 on 2025-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0017_remove_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
