# Generated by Django 5.1.3 on 2025-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0018_remove_userprofile_profile_picture_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
