# Generated by Django 5.1.3 on 2025-01-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_alter_offerdetail_revisions'),
        ('orders_app', '0004_alter_order_business_user_alter_order_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offers_app.offerdetail'),
            preserve_default=False,
        ),
    ]
