# Generated by Django 5.1.3 on 2025-01-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_order_offer_detail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_detail_id',
            new_name='offer_detail',
        ),
    ]
