# Generated by Django 5.1.3 on 2025-01-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_alter_order_revisions'),
        ('users_auth_app', '0018_remove_userprofile_profile_picture_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_offers', to='users_auth_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='users_auth_app.userprofile'),
        ),
    ]
