# Generated by Django 5.1.3 on 2025-01-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_alter_order_business_user_alter_order_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
