# Generated by Django 5.1.3 on 2025-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_offer_min_delivery_time_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='offers/images/'),
        ),
    ]
