# Generated by Django 5.1.3 on 2025-01-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image',
            new_name='file',
        ),
    ]
