# Generated by Django 5.1.3 on 2025-01-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_rename_image_offer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='file',
            new_name='image',
        ),
    ]
