# Generated by Django 5.1.3 on 2025-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='offers/images/'),
            preserve_default=False,
        ),
    ]
