# Generated by Django 5.1.3 on 2025-01-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0012_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='offers/images/'),
        ),
    ]
