# Generated by Django 5.1.3 on 2025-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0013_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(),
        ),
    ]
