# Generated by Django 5.1.3 on 2025-01-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0016_alter_offerdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(),
        ),
    ]
